# Generated by Django 4.2.16 on 2025-01-02 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 2, 17, 24, 39, 423304)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="user_profile",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="app.profile",
            ),
            preserve_default=False,
        ),
    ]
